### ISSUE TITLE
FirebaseConfig.js

### ISSUE THREAD

**Issue by s-marques** [VaibhavEkambaram/Penguin#2]
Sample FirebaseConfig.js is missing

**Comment by VaibhavEkambaram** [comment]
I can provide a sample FirebaseConfig file sometime soon. What may take more time would be to document the structure of the firebase database. Some of this can be inferred from the database calls within the application, but I will be sure to document this a bit more in depth sometime in the future. 

In the meantime, it may be worth having a look at this tutorial, as it covers a lot of the basics:
https://www.freecodecamp.org/news/react-native-firebase-tutorial/

**Comment by VaibhavEkambaram** [comment]
Furthermore, for security reasons, it would be best to create a new firebase database if you wish to work with the software. Forking the project, and then linking this may be helpful for this.

**Comment by VaibhavEkambaram** [comment]
Hey there, I have added an example firebase config setup file in src/config/firebaseconfig.js
This should hopefully get you going
